apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-{{ .Values.type }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: sealed-secrets
    targetRevision: 2.5.19
    helm:
      values: |
        fullnameOverride: sealed-secrets
