apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-secrets-{{ .Values.type }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: {{ .Values.cluster }}
    namespace: {{ .Values.ns }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    repoURL: https://registry.nixys.io/chartrepo/public
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: workload
      values: |
        releasePrefix: "-"
        extraDeploy:
          - kind: SealedSecret
            apiVersion: bitnami.com/v1alpha1
            metadata:
              name: managed-secret-example
              namespace: managed
              creationTimestamp: null
            spec:
              template:
                metadata:
                  name: managed-secret-example
                  namespace: managed
                  creationTimestamp: null
              encryptedData:
                password: AgAyze2WzWKzK0GX8hsc0GBjtxq1h6aPw5QypH2BeBLTZy0mXV1T5NnJp2AB3TwT2bsy/1vKTda8BEXO0uwWoXnGOJuSkrZ9ERtTc1whhFpOccazGHcb/UIEMoHBsprAJkN15GYZ1Gwi7rPjLqz3mQJGRmJv1bzny9z4KsyXF23xn1sSkvl+2w3O3RXvJ3zgkzPU49qHg2E8ejTpw48ip/3K+LJVR18+VDR/U/3CXG7xId0LRZqXKXSjx0OCmAqiOQxxrB0J6A/IHTLgSpdywjXSb5neYcdD0d64nhEhZr7UVrL0U5MNjt5oHfamHGKmPq4XIO5lK1BKmw/3CfUqNfJtoEdDx9gA5y9iqq9K17ASu7U/S09trsQMwqxQbL7StEBy3hwLgdjJtRIPXbVedbyQhgKnbDvdQ/2kEbCSJ2/Y0wyf1CFLPk0xZmN5yIPCZE+jAEtTOdOS7UoXWFKXZXAjHSW2QY6wgxxOMldh31YwE8BjKnAHR0dHpHJR+i6QajCLjEEBe5Zy4M+9obx3DlNfz5RSH+FxeiGN4FQsN0Onp98/6YcUgYLj7ndaz02RWyt1j3/qWpQQzGb+WFwOEN7hI1Vl1b6G5Ag8nwYRcGd7k3iLr5oFR/MwgKCsoIxPCPzP68BpnviB4qMlxf61c8rn03EdhAE/EnAG9QMiykkJd0DOcL7i8RBfCwAfWkQkbAKEAJCwNRQQgBBcmxoJWK67WPp24Q==
