apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-secrets-{{ .Values.type }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: {{ .Values.cluster }}
    namespace: {{ .Values.ns }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    repoURL: https://registry.nixys.io/chartrepo/public
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: workload
      values: |
        releasePrefix: "-"
        extraDeploy:
          - kind: SealedSecret
            apiVersion: bitnami.com/v1alpha1
            metadata:
              name: managed-secret-example
              namespace: managed
              creationTimestamp: null
            spec:
              template:
                metadata:
                  name: managed-secret-example
                  namespace: managed
                  creationTimestamp: null
              encryptedData:
                password: AgAhBOM+nl6vpTaZGGElsG7DHI6loP3EC/bmbK3+yM7gKvePRZSZeQXX5yB8tIeUF+mI1R0IcdaYLN2waFAeUqrI5U2ziM2NVa41Kwwk9j99MpHlYj0zauXZebV+42t6P9KMsdRgP88ON8HUaAaf40/ObU1PpvbbIxhiLr+sO1tQBRdLeJl/Gdq8ZR3CS4dZgEqauH5sR5SYNW2zfdv4z1edLxo4tvD1nTtI3XDNfrvYeO3JELDB7mjbBkE8UiMC2mzDTn/FKCfuKYgtHAYIE+6HhiJUcJZwfa6jzQjNhjZ/s+/+tGLL97cvcHmsEJ/o06Wt7287RZEIXYUpelwrEakixjXsDAFyzZx8vWze7s9xWWtU3SgVk6rT/LMQ0eqSGn/56UrkZZYLuJzdO7kxsRTWKggy4JG+l5ocpLzy2KzCYOdd+6YsoyH3RYVNZkLt2AtdVnXGN0258sRa/NV0bVjAS+z/+pVqM8Aw8f/jP6NUxRFUvVU9da54/E7mk91xZya1E1Ag7OodooKhJZeLzZ4jrDBPZ2XjGEB7D9v+t9Owzn6U+Z5zTlF1bo7fnPLnYitk29xg/dTktmKG5YXuYZKIwXiOffav63BiuCnDmJxT5Mg2SsELWu0JcRqkmXgE48kdd14kzFZVUwVNoYsN4QJ6Zg/VX8rBU1SgxNh2qPLIarUr/IkeOjo1oAUHyUwlVxDs/16zhqdXmqEEw20uE16AEeknUw==
