apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-secrets-{{ .Values.type }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: {{ .Values.cluster }}
    namespace: {{ .Values.ns }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    repoURL: https://registry.nixys.io/chartrepo/public
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: argocd
      values: |
        releasePrefix: "-"
        extraDeploy:
          - kind: SealedSecret
            apiVersion: bitnami.com/v1alpha1
            metadata:
              name: initial-admin-secret
              namespace: argocd
              creationTimestamp: null
            spec:
              template:
                metadata:
                  name: initial-admin-secret
                  namespace: argocd
                  creationTimestamp: null
              encryptedData:
                password: AgBNwJrICehVQhw2IWpmmWkFXu8JmoLJhvXRyh9sUAkgS1Q9Du6I9lmvWs2ip3sw2c8ke6bXCzR0neJ2nUxWM0AAq3A/zeyspXG/ZlUMXDJbOosv78f18bucyZJ8ou8hmcENWVyUeosclBwZgtGtKLB3t7ymDbASTYBMl2QsWYBCGRzSaoRb42ZTOV7j6TK7HicU+NExyGj4Q52WhzzoH+S1LeuYovHw7h4teM37nal0zOTvQGE+K5Q24WK7KSHiNmHKu/z41/soCRKxcZBZr1uKzp+kcot9tYUrXAex2MqjheemHu5Xoij/hcw20eVM7iQGlRUIBtVip7fiI/c1tk1rWF8ZKM3cVSdMKckdLQwkQsgJHydXExYABvek8mFSY/m5vwsmFrbwECnD9IMV17lZLyJ+UAiZyc5s4vXASERGHrl5Nvr2xrq2sfbRMPkgj1Clt071Ofy6R4zFA+rDLDUhOHtxFFYNVxB0Q+/fe/0mdIo/uXgsRYrMxQMav+BfPQlig5l7bUHW3dIji4BQm0mAo/Dum/mFzx5KbCg9kllVVtqHXBga5CTKHzMRLR9WFoaKRf3lGiHXZlyW0JaSY6k4l2wmGtvCXwFjgGUWaTlz79gSTJzs5FDlbpcMn7k4ohfjehLgRaR6naMVA9Surd+iBqUPzc4p1gcWpqT9k/8jY4YC5+MAAT6f+ddCrIi4b5BbeQ0Z+w==
