apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-secrets-{{ .Values.type }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: {{ .Values.cluster }}
    namespace: {{ .Values.ns }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    repoURL: https://registry.nixys.io/chartrepo/public
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: argocd
      values: |
        releasePrefix: "-"
        extraDeploy:
          - kind: SealedSecret
            apiVersion: bitnami.com/v1alpha1
            metadata:
              name: argocd-initial-admin-secret
              namespace: argocd
              creationTimestamp: null
            spec:
              template:
                metadata:
                  name: argocd-initial-admin-secret
                  namespace: argocd
                  creationTimestamp: null
              encryptedData:
                password: AgCrg/zTbByDOam+agkCcHbpza5orbHUGQilwQCD793X+9tNr2o0KiVZ1MttNYk1qQVzqqNbw85j8T69gACK/EHZDG7DT1s+x8fExkfdne97z2GhkbcRsEx0trJgDMJ7rJHvvKLHhYjlaGGa6yH7yYfIWTnEBtgMFg4Z4V9bb6kqoB8iUYiGnxHlMHeJAZUJpabHTGrrBfiEXcEMUVFA0IhcLdF6e4+uJRhc8uuU8db4qG+h7TFbl+cYDt/j1YU3DEjrpFPYKygTMOM4WfuDpazlbweqx5JFu48oJx6Gy4t2/Lne65zavQ8WBLmo2zS0ym3UF1xRModPfKOGbwOiXWhrCzTpdjXKWqVkvXta++xq57qar/BRFM3k/WuEnKWAABUIKeNyxEhmmbNUR3gf+hZBEhUDAhJ/8M2kH8xkIsgUIA2c7KCnTuRVM5RvHI6ZcWAXkd/M6ji7VO8uTGey2QC+zDO16GFWEpwoq1WXemewy/uAnX/oxOF1lIFKDdHPIUv2APm9/qYGncBQwLgwQFPOns36hiI2G5/ImPDbmsFo8YNM0XL4K8+zckMNFOMT6pS5b/jWtIqx+XVncc1zZPSt/n2bumhMqpBOrp623UsQMdiC8HwRIhUukWkFo+jrUKEwp0vJMUp/+0TlFGewv3fDVO705v5wdZFCupc1xOI24+J/fztxDwdhc12s9oNQqhJERv0nOA==
