apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    gitlab.com githubusercontent.com github.com github.io googleapis.com grafana.com nixys.io mirror.yandex.ru hashicorp.com:53 {
      forward . 1.1.1.1
    }