apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-eso-db-secret
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://UndeadDemidov.github.io/charts
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      valuesObject:
        releasePrefix: "-"
        
        extraDeploy:
          secretStore: |-
            apiVersion: external-secrets.io/v1
            kind: SecretStore
            metadata:
              name: vault-backend
              namespace: {{ .Values.ns }}
            spec:
              provider:
                vault:
                  server: "http://vault.workload.svc:8200"
                  path: "kv-v2"
                  version: "v2"
                  auth:
                    kubernetes:
                      mountPath: "kubernetes"
                      role: "eso-role"
                      serviceAccountRef:
                        name: external-secrets

          example-eso-db-secret: |-
            apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: example-eso-db-secret
              namespace: {{ .Values.ns }}
            spec:
              refreshInterval: "15s"

              secretStoreRef:
                name: vault-backend
                kind: SecretStore

              target:
                name: example-eso-db-credentials

              data:
                - secretKey: PGUSER
                  remoteRef:
                    key: in-cluster/infra/workload/database
                    property: username
                - secretKey: PGPASSWORD
                  remoteRef:
                    key: in-cluster/infra/workload/database
                    property: password
