apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo
  namespace: http-echo
spec:
  destination:
    namespace: http-echo
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: http-echo
  source:
    repoURL: 'https://github.com/UndeadDemidov/k3d-argocd-sandbox.git'
    path: argocd/unmanaged/Applications
    targetRevision: 'master'
    helm:
      parameters:
        - name: type
          value: unmanaged
        - name: server
          value: https://kubernetes.default.svc
        - name: cluster
          value: in-cluster
        - name: project
          value: http-echo
        - name: ns
          value: http-echo
