apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  # repoURL: https://cloudnative-pg.github.io/charts
  - repoURL: https://UndeadDemidov.github.io/charts
    chart: cloudnative-pg
    targetRevision: 0.27.1
    helm:
      releaseName: cnpg
      valuesObject:
        monitoring:
          grafanaDashboard:
            create: true
            annotations:
              argocd.argoproj.io/sync-options: ServerSideApply=true

        crds:
          annotations:
            argocd.argoproj.io/sync-options: ServerSideApply=true

  - repoURL: https://UndeadDemidov.github.io/charts
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: log-emitter
      valuesObject:
        releasePrefix: "-"

        extraDeploy:
        - apiVersion: postgresql.cnpg.io/v1
          kind: ClusterImageCatalog
          metadata:
            name: postgresql
          spec:
            images:
              - major: 15
                image: ghcr.io/cloudnative-pg/postgresql:15.14
              - major: 16
                image: ghcr.io/cloudnative-pg/postgresql:16.10
              - major: 17
                image: ghcr.io/cloudnative-pg/postgresql:17.6
              - major: 18
                image: ghcr.io/cloudnative-pg/postgresql:18.1

        - apiVersion: postgresql.cnpg.io/v1
          kind: Cluster
          metadata:
            name: postgres
            namespace: {{ .Values.ns }}
          spec:
            instances: 2

            imageCatalogRef:
              apiGroup: postgresql.cnpg.io
              kind: ClusterImageCatalog
              name: postgresql
              major: 18

            bootstrap:
              initdb:
                database: app
                owner: app
                secret:
                  name: app-secret

            storage:
              size: 1Gi
