apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.54.0
    helm:
      releaseName: "fluentbit"
      valuesObject:
        nameOverride: fluentbit
        
        testFramework:
          enabled: false
        annotations:
          reloader.stakater.com/auto: "true"

        daemonSetVolumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          # - name: etcmachineid
          #   hostPath:
          #     path: /etc/machine-id
          #     type: File

        daemonSetVolumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          # - name: etcmachineid
          #   mountPath: /etc/machine-id
          #   readOnly: true

        luaScripts: {}

        ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
        config:
          ## https://docs.fluentbit.io/manual/pipeline/inputs
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Buffer_Chunk_Size 128k
                Buffer_Max_Size 256k
                Mem_Buf_Limit 50MB
                Skip_Long_Lines On

            [INPUT]
                Name systemd
                Tag host.*
                Systemd_Filter _SYSTEMD_UNIT=kubelet.service
                Read_From_Tail On

          ## https://docs.fluentbit.io/manual/pipeline/filters
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On

            [FILTER]
                Name parser
                Match kube.*
                Key_Name log
                Parser level_extractor
                Reserve_Data On
                Preserve_Key On

            [FILTER]
                Name parser
                Match kube.*
                Key_Name log
                Parser level_bracket_prefix
                Reserve_Data On
                Preserve_Key On

            [FILTER]
                Name parser
                Match kube.*
                Key_Name log
                Parser level_bracket_with_date
                Reserve_Data On
                Preserve_Key On

          ## https://docs.fluentbit.io/manual/pipeline/outputs
          outputs: |
            [OUTPUT]
                Name http
                Match *
                host vl-single-server.{{ .Values.ns }}.svc
                port 9428
                uri /insert/jsonline?_stream_fields=stream,level&_msg_field=msg,log&_time_field=date
                format json_lines
                json_date_format iso8601

          ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers
          ## This configuration is deprecated, please use `extraFiles` instead.
          upstream: {}

          ## https://docs.fluentbit.io/manual/pipeline/parsers
          customParsers: |
            [PARSER]
                Name docker_no_time
                Format json
                Time_Keep Off
                Time_Key time
                Time_Format %Y-%m-%dT%H:%M:%S.%L

            [PARSER]
                Name level_extractor
                Format regex
                Regex .*(lvl|level)=(?<level>[a-zA-Z]+)
                Time_Keep Off

            [PARSER]
                Name level_bracket_prefix
                Format regex
                Regex ^\[(?<level>[A-Z]+)\]\s+(?<message>.*)
                Time_Keep Off

            [PARSER]
                Name level_bracket_with_date
                Format regex
                Regex ^\[[^\]]+\]\s+\[\s*(?<level>\w+)\]\s+(?<message>.*)
                Time_Keep Off