apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://stakater.github.io/stakater-charts 
    chart: reloader
    targetRevision: 2.2.5
    helm:
      valuesObject:
        fullnameOverride: reloader
        reloader:
          deployment:
            resources:
              limits:
                cpu: 150m
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 128Mi
          service:
            port: 9090

  - repoURL: https://registry.nixys.io/chartrepo/public
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: reloader
      valuesObject:
        releasePrefix: "-"

        extraDeploy:
          vmSrvScrape: |-
            kind: VMServiceScrape
            apiVersion: operator.victoriametrics.com/v1beta1
            metadata:
              name: reloader
              namespace: {{ .Values.ns }}
            spec:
              endpoints:
                - port: http
                  path: /metrics
              selector:
                matchLabels:
                  app.kubernetes.io/instance: reloader
                  app.kubernetes.io/name: reloader
