apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://stakater.github.io/stakater-charts 
    chart: reloader
    targetRevision: 2.2.5
    helm:
      valuesObjects:
        reloader:
          deployment:
            resources:
              limits:
                cpu: 150m
                memory: 512Mi
              requests:
                cpu: 10m
                memory: 128Mi
