apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://registry.nixys.io/chartrepo/public
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: sealed-secrets
      valuesObject:
        releasePrefix: "-"

        extraDeploy:
          vmSrvScrape: |-
            kind: VMServiceScrape
            apiVersion: operator.victoriametrics.com/v1beta1
            metadata:
              name: sealed-secrets
              namespace: {{ .Values.ns }}
            spec:
              endpoints:
                - port: metrics
                  path: /metrics
              selector:
                matchLabels:
                  app.kubernetes.io/instance: sealed-secrets
                  app.kubernetes.io/name: sealed-secrets

  - repoURL: https://mirror.yandex.ru/helm/charts.bitnami.com/
    chart: sealed-secrets
    targetRevision: 2.5.19
    helm:
      valuesObject:
        fullnameOverride: sealed-secrets

        metrics:
          enabled: true
