apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://registry.nixys.io/chartrepo/public
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: vault
      valuesObject:
        releasePrefix: "-"
        
        # extraDeploy:
        #   vmSrvScrape: |-
        #     kind: VMServiceScrape
        #     apiVersion: operator.victoriametrics.com/v1beta1
        #     metadata:
        #       name: vault
        #       namespace: {{ .Values.ns }}
        #     spec:
        #       endpoints:
        #         - port: http
        #           path: /api/v2/metrics/prometheus
        #         - port: metrics
        #           path: /metrics
        #       selector:
        #         matchLabels:
        #           app.kubernetes.io/instance: fluentbit
        #           app.kubernetes.io/name: fluentbit

  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.31.0
    helm:
      releaseName: vault
      valuesObject:
        injector:
          enabled: false
        ui:
          enabled: true
          serviceType: NodePort
          serviceNodePort: 30200
        server:
          affinity: ""
          service:
            type: NodePort
            activeNodePort: 30201
            publishNotReadyAddresses: false
          ha:
            enabled: true
            replicas: 3
            raft: 
              enabled: true
              config: |
                ui = true

                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  # Enable unauthenticated metrics access (necessary for Prometheus Operator)
                  telemetry {
                    unauthenticated_metrics_access = "true"
                  }
                }

                storage "raft" {
                  path = "/vault/data"
                }

                service_registration "kubernetes" {}
