apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: "{{ .Values.cluster }}"
    namespace: {{ .Values.ns }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://helm.vector.dev
    chart: vector
    targetRevision: 0.50.0
    helm:
      valuesObject:
        role: Agent
        dataDir: /vector-data-dir
        resources: {}
        args:
          - -w
          - --config-dir
          - /etc/vector/
        containerPorts:
          - name: metrics
            containerPort: 9090
            protocol: TCP
        service:
          enabled: false
        customConfig:
          data_dir: /vector-data-dir
          api:
            enabled: false
            address: 0.0.0.0:8686
            playground: true
          sources:
            k8s:
              type: kubernetes_logs
          transforms:
            parser:
              type: remap
              inputs: [k8s]
              source: |-
                .image = .kubernetes.container_image
                .container = .kubernetes.container_name
                .pod = .kubernetes.pod_name
                .ip = .kubernetes.pod_ip
                .namespace = .kubernetes.pod_namespace
                .node = .kubernetes.pod_node_name

                del(.file)
                del(.kubernetes)

                .log = 
                  parse_json(.message) ??
                  parse_key_value(.message) ??
                  parse_logfmt(.message) ??
                  parse_nginx_log(.message, "main") ??
                  .message

                if exists(.log.level) && .log.level != null && .log.level != "" { .level = .log.level }
                if exists(.log.level_value) {
                  v, err = to_string(.log.level_value)
                  if err == null {
                    .level = if v == "20000" { "info" } else if v == "10000" { "debug" } else if v == "30000" { "warn" } else if v == "40000" { "error" } else if v == "50000" { "fatal" } else if v == "5000" { "trace" } else { .level }
                    .level_value = .log.level_value
                  }
                }

                del(.message)
          sinks:
            vlogs:
              type: elasticsearch
              inputs: [parser]
              endpoints:
                - http://vl-single-server.{{ .Values.ns }}.svc:9428/insert/elasticsearch/
              mode: bulk
              api_version: v8
              compression: gzip
              healthcheck:
                enabled: false
              request:
                headers:
                  VL-Time-Field: timestamp
                  VL-Stream-Fields: stream,node,namespace,pod,container
                  VL-Msg-Field: log,msg,_msg,log.msg,log.message,message
                  AccountID: "0"
                  ProjectID: "0"