apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: RELEASE_NAME-secrets-{{ .Values.type }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  destination:
    name: {{ .Values.cluster }}
    namespace: {{ .Values.ns }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    repoURL: https://registry.nixys.io/chartrepo/public
    chart: nxs-universal-chart
    targetRevision: 2.8.3
    helm:
      releaseName: RELEASE_NAME
      values: |
        releasePrefix: "-"
